language: node_js
cache:
  directories:
    - node_modules
notifications:
  email: false
node_js:
  - '8'
  - '10'
  - 'lts/*'
before_script:
  - npm prune
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
before_install:
  - cd node
